### ISSUE TITLE
Names of resources not returned in the SDK

### ISSUE THREAD

**Issue by cfonze** [IBM/platform-services-go-sdk#137]
The REST API has an optional parameter called _names when set to true, returns the names of the resources such as resource_name, resource_instance_name, and resource_group_name.  This go sdk has ability to set the names parameter equal to true but the usagereportsv4.InstanceUsage struct does not have the resource_name, resource_instance_name, and resource_group_name.  Any chance we can get that implemented or should we just use the REST API?

**Comment by padamstx** [comment]
Awaiting response from service team member.

**Comment by padamstx** [comment]
Assigning to Andras for tracking purposes for now.

**Comment by padamstx** [comment]
I believe the Usage Reports service within the Go SDK has been updated to include the additional "name"-related properties within various response structs.   
@cfonze Could you please give this another try to confirm?
