### ISSUE TITLE
result.id of GET accountsettings function of cloudshell is returning nil

### ISSUE THREAD

**Issue by kavya498** [IBM/platform-services-go-sdk#159]
**Describe the bug**
result.id of [GET accountsettings function of cloudshell](https://github.com/IBM/platform-services-go-sdk/blob/main/ibmcloudshellv1/ibm_cloud_shell_v1.go#L172) is returning nil 

**Expected behavior**
It should have returned unique ID

**Comment by padamstx** [comment]
@kavya498 I ran the Go SDK integration test for the service and here are the debug request/response messages for the GetAccountSettings operation:
```
2021/10/29 13:09:22 [Debug] Request:
GET /api/v1/user/accounts/2de836702ef00a3435bab2a105c5452b/settings HTTP/1.1
Host: api.shell.cloud.ibm.com
User-Agent: platform-services-go-sdk/0.22.2 (lang=go; arch=amd64; os=linux; go.version=go1.16.8)
Accept: application/json
Authorization: [redacted]
Accept-Encoding: gzip


2021/10/29 13:09:22 [DEBUG] GET https://api.shell.cloud.ibm.com/api/v1/user/accounts/2de836702ef00a3435bab2a105c5452b/settings
2021/10/29 13:09:22 [Debug] Response:
HTTP/2.0 200 OK
Cf-Cache-Status: DYNAMIC
Cf-Ray: 6a5e5ac4694e67a8-DFW
Content-Type: application/json; charset=utf-8
Date: Fri, 29 Oct 2021 18:09:22 GMT
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
X-Request-Id: 497ab6e8-bd89-485c-bd46-f843238e7cdd

{"type":"account_settings","account_id":"2de836702ef00a3435bab2a105c5452b","enabled":true,"regions":[{"key":"eu-de","enabled":true},{"key":"jp-tok","enabled":true},{"key":"us-south","enabled":true}],"default_enable_new_regions":true,"features":[{"key":"server.file_manager","enabled":true},{"key":"server.web_preview","enabled":true}],"default_enable_new_features":true}
```
And you can see that the `_id` field is not present in the response body, so this is why you're not seeing that being unmarshalled.   Looks like this is a problem with the server if the `_id` field should in fact be returned in all scenarios.
I think you'll need to pursue this with the service team so the problem can be addressed in the service implementation.

**Comment by padamstx** [comment]
@hartyt ^^^

**Comment by padamstx** [comment]
BTW, it looks like the following fields from the "AccountSettings" schema are missing from the operation's response:
`_id`, `_rev`, `created_at`, `created_by`, `updated_at`, `updated_by`.

**Comment by seancallanan** [comment]
@padamstx I'm not familiar with the sdk but I tried to do an example:

`package main

import (
    "github.com/IBM/platform-services-go-sdk/ibmcloudshellv1"
    "fmt"
	"encoding/json"
)

var accountID="681694096ef8338ad439a95a1b897e00"

func main() {
    serviceClientOptions := &ibmcloudshellv1.IBMCloudShellV1Options{}
    ibmCloudShellService, err := ibmcloudshellv1.NewIBMCloudShellV1UsingExternalConfig(serviceClientOptions)
    getAccountSettingsOptions := &ibmcloudshellv1.GetAccountSettingsOptions{
        AccountID: &accountID,
    }

    accountSettings, _, err := ibmCloudShellService.GetAccountSettings(getAccountSettingsOptions)
    if err != nil {
        panic(err)
    }
    b, _ := json.MarshalIndent(accountSettings, "", "  ")
    fmt.Println(string(b))
    fmt.Println(*accountSettings.ID)
}` 

I get all the values printed out and I get the ID printed.  Am I missing something or is this a bug only affecting particular accounts?

**Comment by padamstx** [comment]
Not sure why the service would behave differently for different accounts, if that is in fact happening.   I've contacted the team that supports the service, so hopefully they'll have some answers soon.

**Comment by seancallanan** [comment]
Sorry @padamstx I'm from the team.

The issue we are seeing happens only the first time a user access the AccountSettings because there is no database entry created.  You should be able to update the settings and in the process all those fields will be created.

**Comment by padamstx** [comment]
@seancallanan 
> Sorry @padamstx I'm from the team.

Oh, sorry about that... I had pinged Bo on slack and didn't know that you were working on the cloudshell service :)

From a user's standpoint, it seems weird that they would first need to update the account settings before they can retrieve the account settings (and see all the fields filled in) for an existing account.  This seems sorta like a bug in the service to me.   The GET operation has a certain set of properties defined in the response, and only some of them are getting set.
Would it be possible to modify the behavior of the GET operation so that if there is no db entry, the service first creates one so that the server-provided property values are populated, then it returns the full response (including all the currently missing properties)?   What do you think?

**Comment by padamstx** [comment]
Thanks @seancallanan Could you add a link to the new issue here as well?

@kavya498 Once Sean provides the link to the new issue, can we close this out?  You could then monitor the other issue for when the service will be updated.  Once that change is made, the Go SDK behavior should just change accordingly.

**Comment by seancallanan** [comment]
> @kavya498 Given the above discussion about the current behavior of the GET operation, it seems like that would cause some potential issues in the terraform provider, wouldn't it? I mean... it seems like the terraform provider would be much more straightforward if the GET operation just always returned the values associated with the server-populated properties (e.g. `_id`, `_rev`, etc.).

https://github.ibm.com/cloudshell/cloudshell-api/issues/262

**Comment by padamstx** [comment]
Since this issue will need to be addressed in the cloudshell service implementation, I've cc'd Kavya in the cloudshell issue linked above, and I will close out this one...
@kavya498 Please follow the above issue for info about when the problem has been resolved.
