### ISSUE TITLE
Add API for list Cloudant Instances properties

### ISSUE THREAD

**Issue by bigdatasourav** [IBM/platform-services-go-sdk#161]
**Is your feature request related to a problem? Please describe.**
The existing API calls for Cloudant do not include the instance properties.
Attached is a sample.
![image](https://user-images.githubusercontent.com/78197905/138092813-2ed9013d-b820-4d34-ab7e-68c8b510b62a.png)
**Describe the solution you'd like**
Want to list out the cloudant instance properties like - CRN, Endpoint, Encryption details.

**Describe alternatives you've considered**
We have already tried with cloudant sdk -https://github.com/IBM/cloudant-go-sdk

**Additional context**

**Comment by padamstx** [comment]
This repository is a Go SDK for the [IBM Cloud Platform Services](https://cloud.ibm.com/docs?tab=api-docs&category=platform_services) which doesn't include the Cloudant service.   Please contact the maintainers of https://github.com/IBM/cloudant-go-sdk for assistance.

**Comment by ricellis** [comment]
>The existing API calls for Cloudant do not include the instance properties.

@bigdatasourav - I think it would help if you could describe _which_ existing API call doesn't include the properties.
Anyway based on the screenshot - I think the API call you should be using is in the `Resource Controller V2 API` (@padamstx that one [lives here](https://github.com/IBM/platform-services-go-sdk/tree/main/resourcecontrollerv2) right?)
I think the specific API call you need is: https://cloud.ibm.com/apidocs/resource-controller/resource-controller?code=go#get-resource-instance

You can see from the response structure there that it will contain the CRN, region_id etc.
Cloudant instance specific details (e.g. endpoint) are in the `extensions` object (though it may depend on your instance I believe older instances _do not_ have those properties available).

**Comment by padamstx** [comment]
> @padamstx that one [lives here](https://github.com/IBM/platform-services-go-sdk/tree/main/resourcecontrollerv2) right?

Yes, I was mistaken due to the reference to the Cloudant API.
