### ISSUE TITLE
Unable to find audit logging information for IBM Cloud Identity and Access Management from Activity Tracker.

### ISSUE THREAD

**Issue by bigdatasourav** [IBM/platform-services-go-sdk#162]
**Is your feature request related to a problem? Please describe.**
Unable to find audit logging information for IBM Cloud Identity and Access Management from Activity Tracker API.

**Describe the solution you'd like**
API support for audit logging information for IBM Cloud Identity and Access Management.

**Describe alternatives you've considered**

**Additional context**
Is there any other API to fetch audit logging information for IAM.

**Comment by padamstx** [comment]
@pooraniss-ibm Could you please help with this issue?

**Comment by pooraniss-ibm** [comment]
@bigdatasourav sorry I dont fully understand the ask.. can you please give me more information please

**Comment by bigdatasourav** [comment]
@padamstx @pooraniss-ibm sorry for the delayed response on it, here is what we want in terms of support from you,
The below API for Activity Tracker supports, route & target-related information

https://github.com/IBM/platform-services-go-sdk/blob/main/atrackerv1/atracker_v1.go

We would like to track audit logging information for IBM Cloud Identity and Access Management as per this [doc](https://cloud.ibm.com/docs/activity-tracker?topic=activity-tracker-at_events_iam). Any suggestion on how do we achieve this? We are automating a few controls to track these activities as part of IBM CIS (1.18 Enable audit logging for IBM Cloud Identity and Access Management). Any forward direction will help. Happy to provide more information further.
