### ISSUE TITLE
Enumerating power-iaas services

### ISSUE THREAD

**Issue by hamzy** [IBM/platform-services-go-sdk#203]
I created a sample program:

https://gist.github.com/hamzy/16f278cecfefb460f95f68745e210dd3

which calls NewListResourceInstancesOptions and then ListResourceInstancesWithContext.  I see a bunch of resources but no Power Systems Virtual Servers.  What am I doing wrong?

**Comment by padamstx** [comment]
@apoorva9s14 Could you please help with this RC-related question?

**Comment by padamstx** [comment]
cc: @phanziii

**Comment by phanziii** [comment]
@hamzy - your sample program looks correct, but your query filter is very coarse and thus, will return back over 200+ instances (assuming you have access to view them).  Can I ask if you're able to add in the following filters and retry?

options.SetResourceGroupID("c1cb9b2679344ee9951ab8b4bc22eca0")
options.SetResourceID("abd259f0-9990-11e8-acc8-b9f54a8f1661") // resource Id for Power Systems Virtual Server in the Global catalog

Also if you retried this using the RC APIs or Cloud CLI do these instances for Power Systems Virtual Server return for you?

**Comment by hamzy** [comment]
> @hamzy - your sample program looks correct, but your query filter is very coarse and thus, will return back over 200+ instances (assuming you have access to view them). Can I ask if you're able to add in the following filters and retry?
> 
> options.SetResourceGroupID("c1cb9b2679344ee9951ab8b4bc22eca0") options.SetResourceID("abd259f0-9990-11e8-acc8-b9f54a8f1661") // resource Id for Power Systems Virtual Server in the Global catalog

Thanks!  I recompiled with your suggestion.  I can now see:

```
hamzy:powervs-hack$ (export IBMCLOUD_API_KEY="blah"; cd list-service-instances/; go run list-service-instances.go) 2>&1 | tee output.errors 
hamzy:powervs-hack$ grep 'resource: ' output.errors 
2022/08/29 10:02:41 resource: powervs-ipi-fra02
2022/08/29 10:02:41 resource: powervs-ipi-syd04
2022/08/29 10:02:41 resource: powervs-ipi-lon06
2022/08/29 10:02:41 resource: powervs-ipi-fra02-bad
2022/08/29 10:02:42 resource: powervs-ipi-syd05
2022/08/29 10:02:42 resource: powervs-ipi-mon01
2022/08/29 10:02:42 resource: rdr-cln-ipi-tor01
2022/08/29 10:02:42 resource: powervs-ipi-tok04
2022/08/29 10:02:42 resource: powervs-ipi-osa21
2022/08/29 10:02:42 resource: powervs-karthik-03-sao
2022/08/29 10:02:43 resource: powervs-ipi-karthik-sao01
2022/08/29 10:02:43 resource: rdr-kumarmn-ipi-tok04
2022/08/29 10:02:43 resource: rdr-kumarmn-ocp-ipi-tok04
2022/08/29 10:02:43 resource: rdr-kumarmn-ipi-tok04-weekend
2022/08/29 10:02:43 resource: rdr-kumarmn-ipi-tok04-never-seems-to-work
```

The list isn't equivalent to what I can see at https://cloud.ibm.com/resources

> Also if you retried this using the RC APIs or Cloud CLI do these instances for Power Systems Virtual Server return for you?

I think this is what you are asking me about:

```
hamzy:powervs-hack$ ibmcloud resource service-instances 2>&1 | grep '^powervs-ipi'
powervs-ipi-cis                                        global     active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-fra02                                      eu-de-2    active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-fra02-bad                                  eu-de-2    active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-karthik-sao01                              sao01      active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-lon06                                      lon06      active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-mon01                                      mon01      active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-osa21                                      osa21      active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-syd04                                      syd04      active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-syd05                                      syd05      active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
powervs-ipi-tok04                                      tok04      active     service_instance   c1cb9b2679344ee9951ab8b4bc22eca0   
```

FYI I can edit these out if any of the information is confidential.

And also FYI, this work is going into the OpenShift IPI installer...

**Comment by hamzy** [comment]
Also BTW, this listing doesn't match the code either
```
hamzy:powervs-hack$ ibmcloud pi service-list --json | jq -r '.[].Name'
```

**Comment by phanziii** [comment]
@hamzy - I checked and your first list of 15 instances from `Thanks! I recompiled with your suggestion. I can now see:` is what I see.  Additionally, I was able to find the instance with name `powervs-ipi-cis` and it's in the same resource group but its resource_id is `75874a60-cb12-11e7-948e-37ac098eb1b9` - which pertains to service **Internet Services**.

Additionally, for the listing from https://cloud.ibm.com/resources, can you provide the diff from your SDK program?

**Comment by hamzy** [comment]
Thanks for the online and offline help @phanziii!  Closing for now...
