### ISSUE TITLE
[Usage Reports] Incorrect json key for Billing Month field in usage summary

### ISSUE THREAD

**Issue by BitForger** [IBM/platform-services-go-sdk#213]
The JSON key seems to have changed on the IBM cloud endpoints for summary.
`v4/accounts/{{account_id}}/summary/{{month}}`

As seen here,
https://github.com/IBM/platform-services-go-sdk/blob/10d182b7a07de5a0811226196b475a823e33766d/usagereportsv4/usage_reports_v4.go#L708
the json key used to be `billing_month` but as seen in the API response the key is now just `month`.
![CleanShot 2022-10-27 at 14 14 49](https://user-images.githubusercontent.com/7409480/198367270-f00af27c-9d88-49fb-ac84-cf8b7aa0a6ed.png)

**Comment by padamstx** [comment]
The production version of the API definition defines "billing_month" in the "Account_Summary" schema (the response schema for the operation).
Where/how did you "discover" this perceived mis-match?

**Comment by BitForger** [comment]
The screenshot I have in the main body of the ticket is an actual production response I got today.

**Comment by padamstx** [comment]
Ok, in that case it looks like the server behavior has changed and the API definition has not been updated to stay in sync.   Please open an issue against the Usage Reports team to report this inconsistency.  Once the API definition has been corrected to reflect the current server behavior, then the SDK code for the service will need to be re-generated from the updated API definition.

**Comment by padamstx** [comment]
cc: @KRuelY

**Comment by padamstx** [comment]
@BitForger I've opened this issue against the Usage Reports service:
https://github.ibm.com/BSS/metering-deliverables/issues/1664

**Comment by BitForger** [comment]
Sweet. Thanks @padamstx
