### ISSUE TITLE
globalcatalogv1.PricingGet: error unmarshalling property metrics -  property 'charge_unit_quantity'

### ISSUE THREAD

**Issue by JohnPaulParkin** [IBM/platform-services-go-sdk#247]
**Describe the bug**

When attempting to retrieve the pricing information via `GlobalCatalogV1.GetPricing` API an unmarshalling exception is thrown : 

> error unmarshalling globalcatalogv1.PricingGet: error unmarshalling property 'metrics' as []globalcatalogv1.Metrics: error unmarshalling property 'charge_unit_quantity': json: cannot unmarshal number into Go value of type string

The cause seems to be that the payload from the REST API returns the `charge_unit_quantity` as a integer but the SDK is expecting that field to be a string.

**To Reproduce**

The sample code from the API doc reproduces the problem with either a kubernetes or postgresql value.  I 
also attached this simple application : [simple2.go.zip](https://github.com/IBM/platform-services-go-sdk/files/11305591/simple2.go.zip)

```
$ go run simple2.go
panic: error unmarshalling globalcatalogv1.PricingGet: error unmarshalling property 'metrics' as []globalcatalogv1.Metrics: error unmarshalling property 'charge_unit_quantity': json: cannot unmarshal number into Go value of type string

goroutine 1 [running]:
main.main()
	/Users/user/temp/pricing/bug/simple2.go:39 +0x1c8
exit status 2
```

----- 

calling the REST API to retrieve the data
`curl -H"Authentication: Bearer $TOKEN" -H"Accept: application/json" https://globalcatalog.cloud.ibm.com/api/v1/public.containers.kubernetes.b1c.32x128:ca-tor28613/pricing`

produces a payload like : 
```
{
  "deployment_id": "public.containers.kubernetes.b1c.32x128:ca-tor28613",
  "deployment_location": "ca-tor",
  "deployment_region": "DEFAULT",
  "origin": "pricing_catalog",
  "type": "Paid",
  "i18n": {},
  "starting_price": {},
  "effective_from": "2023-04-01T00:00:00Z",
  "effective_until": "2023-04-30T23:59:59.999Z",
  "metrics": [
    {
      "part_ref": "",
      "metric_id": "D1SL6LL",
      "tier_model": "Step Tier",
      "resource_display_name": "",
      "charge_unit_display_name": "",
      "charge_unit_name": "instance_hours",
      "charge_unit": "Instance-Hours",
      "charge_unit_quantity": 1,  <<<<<<<<<<<<<<<<<<<<< Note this is an integer
      "amounts": [
```

and the `ChangeUnitQuantity` in the Metrics definition is a string - see code https://github.com/IBM/platform-services-go-sdk/blob/main/globalcatalogv1/global_catalog_v1.go#L3219

**Expected behavior**

The application should not panic when retrieving the values.

**Must gather (please complete the following information):**
 - SDK Version : `0.35.1` and `0.36.0`
 - Go Version : `go1.19.8`
 - Name of service that you're trying to use : `globalcatalogv1`
 - Name of operation that you're trying to invoke :`PricingGet`

**Comment by padamstx** [comment]
This looks like a clear-cut case of the API definition being out of sync with the server implementation.  In the production version of the API definition (https://github.ibm.com/cloud-api-docs/resource-catalog/blob/production/global-catalog.json), the Metrics schema is defined with `charge_unit_quantity` defined as a string but looks like it should be an integer as that's what the server is returning.

To fix, the responsible service team will need to fix the API to match the server implementation, then re-gen the SDK code in each of the 4 SDKs.

**Comment by dubee** [comment]
@JohnPaulParkin, we've released a new version of the GC SDK for golang. Can you please verify the fix?

**Comment by JohnPaulParkin** [comment]
@dubee - thanks for quick turnaround on the fix - I can confirm this addresses the problem that I was hitting and this issue can be closed.
