### ISSUE TITLE
Missing fields in ResourceInstance for the resource controller v2 API

### ISSUE THREAD

**Issue by pdettori** [IBM/platform-services-go-sdk#50]
**Describe the bug**
Some fields that can be retrieved with REST calls to the API are not modeled in the ResourceInstance type, thus cannot be retrieved with the SDK.

**To Reproduce**
1. Create an instance of the cloud object store service using the resource controller v2 API.
2. Retrieve the instance using the SDK and the REST API
3. Compare fields from SDK and REST API

**Expected behavior**
I would expect to find the same fields from the REST call in the ResourceInstance. More specifically, the following fields are missing:

- region_id 
- parameters

Note that `region_id` is not even documented in the [OpenAPI V3 specs for the ResourceController](https://cloud.ibm.com/apidocs/resource-controller/resource-controller#get-resource-instance), while `parameters` is documented in the specs but is not present in the `ResourceInstance` struct.

**Must gather (please complete the following information):**
 - SDK Version [e.g. 1.2.1] - v0.12.1
 - Go Version [e.g. 1.12.15] - 1.14.10
 - Name of service that you're trying to use (if applicable) - cloud-object-storage
 - Name of operation that you're trying to invoke (if applicable) - GetResourceInstance

**Additional context**
Were you able to avoid the problem by changing your application code slightly? No

Here is the JSON file for the REST API call to retrieve the service instance:
[v2-instance.json.txt](https://github.com/IBM/platform-services-go-sdk/files/5448084/v2-instance.json.txt)

There are also other fields missing when comparing the output from the REST API with the struct, but I am not currently using them - for completeness they are the following: 
- created_by
- updated_by
- deleted_by
- scheduled_reclaim_at
- restored_at
-scheduled_reclaim_by
- restored_by
-migrated
-controlled_by.

**Comment by mkistler** [comment]
It looks like the `parameters` field was only recently added to the API defn -- by [this commit](https://github.ibm.com/cloud-api-docs/resource-controller/commit/b2112bd19b036be6e01580bd6d2989a023a1f1fa).  My guess is that we have not regenerated the Resource Controller service since that update.

**Comment by padamstx** [comment]
@pdettori Thanks for finding this.  I'll follow up with the service team to get the API definition updated, then re-generate the service in the SDK.

**Comment by padamstx** [comment]
@pdettori I've discussed this issue with one of the tech leads of the resource controller team, and also opened an issue to get the API definition updated.   As soon as that is done, I can re-generate the SDK code.
Thanks again for reporting this.

**Comment by padamstx** [comment]
@pdettori A new version of the Go SDK (https://github.com/IBM/platform-services-go-sdk/releases/tag/v0.12.2) contains a re-gen of the Resource Controller service using the updated API definition.
Note that the "region_id" property was not added to the ResourceInstance schema because the service team does not want to expose that publicly, but I believe all the rest of the properties are now there.
