### ISSUE TITLE
Missing fields in ResourceKey (resource controller v2)

### ISSUE THREAD

**Issue by pdettori** [IBM/platform-services-go-sdk#57]
**Describe the bug**
The JSON returned by GetResourceKey has "parameters" in the response, but it is not in the documentation or in the SDK. See example in "parameters".

**To Reproduce**
See example in https://cloud.ibm.com/apidocs/resource-controller/resource-controller#get-resource-key

**Expected behavior**
I would expect the SDK / docs to include the "Parameters" field, since it is present in the JSON.

**Must gather (please complete the following information):**
 - SDK Version: 0.14.1
 - Go Version: go1.14.10 darwin/amd64
 - Name of service that you're trying to use: cos-object-storage 
 - Name of operation that you're trying to invoke: GetResourceKey

**Additional context**
Were you able to avoid the problem by changing your application code slightly?
No

**Comment by mkistler** [comment]
I just tested this and as best I can tell the `parameters` field is _not_ returned by `get_resource_key`.  The way I tested was to update one of my existing keys to add a `parameters` property, and then did a `get` on that key and the response does not contain a `parameters` field.

**Comment by jorge-vega6** [comment]
Hello, please excuse my late response, we've just updated the API docs with a disclaimer specifying that some of the API responses might have additional fields that are not documented, these are subject to change and should not be used. Thank you for bringing this up and sorry for any inconveniences it might've caused.

**Comment by pdettori** [comment]
Thank you @mkistler @jorge-vega6  for looking into this. It seems a bit confusing that one can set some parameter in the request but cannot see what it has been set looking at the resource, but ok, closing for now.
