### ISSUE TITLE
Ability to list default resource Group

### ISSUE THREAD

**Issue by kavya498** [IBM/platform-services-go-sdk#78]
Add `default` parameter to ListResourceGroups
CLI and api Provides ability to list default resource group 
CLI-  `ibmcloud resource groups --default`
API - ` /v2/resource_groups?account_id=XXXX&default=true`

SDK doesnt have any such attribute in [request payload ](https://github.com/IBM/platform-services-go-sdk/blob/1eb450bba3237e72388c184d3fdfde900758a0bb/resourcemanagerv2/resource_manager_v2.go#L706)

**Comment by padamstx** [comment]
I assume that you're referring to the list_resource_groups operation in the Resource Manager service, documented here:
https://cloud.ibm.com/apidocs/resource-controller/resource-manager#list-resource-groups

If that's correct, then that operation doesn't support a "default" query param... at least it's not defined in the API definition.

If the service team wants to define that, they can update the API definition and then I can re-generate the SDK code from that after the update.   I'll close this issue as this request would need to go through the Resource Manager team.
